/**
 * Cascading Geo Hierarchy API route.
 *
 * GET /api/geo/hierarchy — returns available country -> state -> city tree
 * based on data indexed in Elasticsearch or DataStore.
 */

import { Router, Request, Response } from 'express';

const router = Router();

// Static India-focused geo tree as base (always available)
const DEFAULT_GEO_TREE: Record<string, Record<string, string[]>> = {
  India: {
    Gujarat: ['Ahmedabad', 'Surat', 'Vadodara', 'Rajkot', 'Bhavnagar', 'Jamnagar', 'Gandhinagar', 'Junagadh', 'Anand', 'Navsari', 'Morbi', 'Bharuch', 'Vapi', 'Porbandar', 'Bhuj', 'Godhra', 'Patan', 'Palanpur'],
    Maharashtra: ['Mumbai', 'Pune', 'Nagpur', 'Thane', 'Nashik', 'Aurangabad', 'Solapur', 'Amravati'],
    Delhi: ['New Delhi', 'North Delhi', 'South Delhi', 'East Delhi', 'West Delhi', 'Delhi'],
    UttarPradesh: ['Lucknow', 'Kanpur', 'Varanasi', 'Agra', 'Noida', 'Prayagraj', 'Meerut', 'Ghaziabad'],
    Punjab: ['Ludhiana', 'Amritsar', 'Jalandhar', 'Patiala', 'Bathinda'],
    WestBengal: ['Kolkata', 'Howrah', 'Durgapur', 'Asansol', 'Siliguri'],
    Karnataka: ['Bengaluru', 'Mysuru', 'Mangaluru', 'Hubli', 'Belagavi'],
    TamilNadu: ['Chennai', 'Coimbatore', 'Madurai', 'Tiruchirappalli', 'Salem'],
    Rajasthan: ['Jaipur', 'Jodhpur', 'Udaipur', 'Kota', 'Bikaner'],
    Kerala: ['Thiruvananthapuram', 'Kochi', 'Kozhikode', 'Thrissur'],
    Telangana: ['Hyderabad', 'Warangal', 'Nizamabad'],
    AndhraPradesh: ['Visakhapatnam', 'Vijayawada', 'Guntur']
  },
};

// Helper to find country and state for a city
function getGeoForCity(city: string) {
  const cityLower = city.toLowerCase();

  // Handle fuzzy state-level regions generated by live-fetch
  if (cityLower.endsWith(' (region)')) {
    const stateName = cityLower.replace(' (region)', '');
    for (const [country, states] of Object.entries(DEFAULT_GEO_TREE)) {
      for (const [state, cities] of Object.entries(states)) {
        if (state.toLowerCase() === stateName) return { country, state, city };
      }
    }
  }

  for (const [country, states] of Object.entries(DEFAULT_GEO_TREE)) {
    for (const [state, cities] of Object.entries(states)) {
      if (cities.some(c => c.toLowerCase() === cityLower || cityLower.includes(c.toLowerCase()) || c.toLowerCase().includes(cityLower))) return { country, state, city };
    }
  }
  return { country: 'India', state: 'Other', city };
}

router.get('/hierarchy', (req: Request, res: Response) => {
  try {
    const dataStore = req.app.locals.dataStore;
    const { language, platform, keyword, threat_category, geo_location } = req.query;

    const { data: posts } = dataStore.getPosts({
      language: language as string,
      platform: platform as string,
      keyword: keyword as string,
      threat_category: threat_category as string,
      geo_location: geo_location as string,
    });

    const nodesMap = new Map<string, any>();

    const getOrCreateNode = (level: string, name: string, parent: string | null) => {
      const key = `${level}-${name}`;
      if (!nodesMap.has(key)) {
        nodesMap.set(key, {
          level,
          name,
          parent,
          post_count: 0,
          lats: [],
          lngs: [],
        });
      }
      return nodesMap.get(key);
    };

    posts.forEach((post: any) => {
      if (!post.geo_location?.city || !post.geo_location.lat || !post.geo_location.lng) return;
      
      const { country, state, city } = getGeoForCity(post.geo_location.city);
      const lat = post.geo_location.lat;
      const lng = post.geo_location.lng;

      const countryNode = getOrCreateNode('country', country, null);
      countryNode.post_count++;
      countryNode.lats.push(lat);
      countryNode.lngs.push(lng);

      const stateNode = getOrCreateNode('state', state, country);
      stateNode.post_count++;
      stateNode.lats.push(lat);
      stateNode.lngs.push(lng);

      const cityNode = getOrCreateNode('city', city, state);
      cityNode.post_count++;
      cityNode.lats.push(lat);
      cityNode.lngs.push(lng);
    });

    const TRUE_CENTROIDS: Record<string, { lat: number, lng: number }> = {
      'India': { lat: 20.5937, lng: 78.9629 },
      'Gujarat': { lat: 22.2587, lng: 71.1924 },
      'Maharashtra': { lat: 19.7515, lng: 75.7139 },
      'Delhi': { lat: 28.7041, lng: 77.1025 },
      'UttarPradesh': { lat: 26.8467, lng: 80.9462 },
      'Punjab': { lat: 31.1471, lng: 75.3412 },
      'WestBengal': { lat: 22.9868, lng: 87.8550 },
      'Karnataka': { lat: 15.3173, lng: 75.7139 },
      'TamilNadu': { lat: 11.1271, lng: 78.6569 },
      'Rajasthan': { lat: 27.0238, lng: 74.2179 },
      'Kerala': { lat: 10.8505, lng: 76.2711 }
    };

    const nodes = Array.from(nodesMap.values()).map(node => {
      let finalCentroid = {
        lat: node.lats.reduce((a: number, b: number) => a + b, 0) / node.lats.length,
        lng: node.lngs.reduce((a: number, b: number) => a + b, 0) / node.lngs.length,
      };

      if ((node.level === 'country' || node.level === 'state') && TRUE_CENTROIDS[node.name]) {
        finalCentroid = TRUE_CENTROIDS[node.name];
      }

      const bounds = [
        [Math.min(...node.lats), Math.min(...node.lngs)],
        [Math.max(...node.lats), Math.max(...node.lngs)],
      ];
      return {
        level: node.level,
        name: node.name,
        parent: node.parent,
        post_count: node.post_count,
        centroid: finalCentroid,
        bounds,
      };
    });

    res.json({
      tree: DEFAULT_GEO_TREE,
      nodes,
    });
  } catch (err) {
    console.error('Error in /hierarchy:', err);
    res.json({ tree: DEFAULT_GEO_TREE, nodes: [] });
  }
});

export default router;
