"""
Jinja2-based escalation notice template for high-severity alerts.

Generates formatted escalation notices when alert severity crosses
the configured threshold. Used for automated analyst notifications
and law-enforcement handoff.

Templates:
  - escalation_notice: Full escalation notice with all context
  - brief_alert: Short notification for SMS/webhook push
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from typing import Any, Optional

try:
    from jinja2 import Environment, BaseLoader
except ImportError:
    # Fallback for environments without Jinja2
    Environment = None  # type: ignore
    BaseLoader = None  # type: ignore

logger = logging.getLogger(__name__)


# ── Escalation Notice Template ──────────────────────────────────────────────

ESCALATION_NOTICE_TEMPLATE = """
================================================================================
                    NETRA — AUTOMATED ESCALATION NOTICE
================================================================================
Priority:        {{ "CRITICAL" if severity >= 5 else "HIGH" if severity >= 4 else "ELEVATED" }}
Alert ID:        {{ alert_id }}
Severity:        {{ severity }}/5
Timestamp:       {{ timestamp }}
Classification:  {{ threat_category }}
Confidence:      {{ "%.1f" | format(confidence * 100) }}%
================================================================================

TRIGGERING REASON:
{{ triggering_reason }}

{% if post_text %}
ORIGINAL POST CONTENT:
─────────────────────────────────────────────────────────────────
{{ post_text[:500] }}{% if post_text|length > 500 %}... [TRUNCATED]{% endif %}
─────────────────────────────────────────────────────────────────
{% endif %}

POST METADATA:
  Platform:      {{ platform }}
  Author:        {{ author_handle }}
  Author ID:     {{ author_id }}
  Language:      {{ detected_language }}
  Location:      {{ geo_location or "Not Available" }}
  Created:       {{ post_created_at }}
  Engagement:    {{ likes }} likes, {{ shares }} shares, {{ comments }} comments

{% if bot_cluster_id %}
BOT CLUSTER DETECTED:
  Cluster ID:    {{ bot_cluster_id }}
  ⚠️  This post is part of a coordinated campaign. See network analysis
     for full cluster details.
{% endif %}

{% if sentiment %}
SENTIMENT ANALYSIS:
  Sentiment:     {{ sentiment }} (intensity: {{ "%.2f" | format(sentiment_intensity) }})
{% endif %}

RECOMMENDED ACTIONS:
{% for action in recommended_actions %}
  {{ loop.index }}. {{ action }}
{% endfor %}

ESCALATION PATH:
  1. Acknowledge this alert in the NETRA Dashboard
  2. Review full post context and network graph
  3. Generate detailed incident report for handoff
  4. Coordinate with platform provider if takedown warranted
  5. File report with relevant law enforcement if applicable

NOTE: NETRA is an analyst-assist tool. It DOES NOT auto-suspend accounts
or auto-remove content. All enforcement actions require human approval.

Generated by: NETRA v1.0 — National-language Event & Threat Recognition Analyzer
================================================================================
"""


BRIEF_ALERT_TEMPLATE = """[NETRA {{ "CRITICAL" if severity >= 5 else "HIGH" if severity >= 4 else "ALERT" }}] \
Severity {{ severity }}/5 — {{ threat_category }} detected on {{ platform }} \
by {{ author_handle }}. Confidence: {{ "%.0f" | format(confidence * 100) }}%. \
{{ triggering_reason[:120] }}{% if triggering_reason|length > 120 %}...{% endif %} \
Alert ID: {{ alert_id }}"""


# ── Template Renderer ───────────────────────────────────────────────────────


class EscalationTemplateRenderer:
    """
    Renders escalation notices from alert and post data using Jinja2.

    Falls back to simple string formatting if Jinja2 is not available.
    """

    def __init__(self, severity_threshold: int = 3):
        """
        Args:
            severity_threshold: Minimum severity level to trigger escalation.
        """
        self.severity_threshold = severity_threshold

        if Environment and BaseLoader:
            self._env = Environment(loader=BaseLoader())
            self._notice_tmpl = self._env.from_string(ESCALATION_NOTICE_TEMPLATE)
            self._brief_tmpl = self._env.from_string(BRIEF_ALERT_TEMPLATE)
            self._jinja_available = True
        else:
            self._jinja_available = False
            logger.warning(
                "Jinja2 not available — escalation templates will use basic formatting"
            )

    def should_escalate(self, severity: int) -> bool:
        """Check if an alert severity meets the escalation threshold."""
        return severity >= self.severity_threshold

    def _get_recommended_actions(
        self, threat_category: str, severity: int, bot_cluster_id: Optional[str]
    ) -> list[str]:
        """Generate context-appropriate recommended actions."""
        actions = []

        if threat_category == "IncitementToViolence":
            actions.extend([
                "IMMEDIATE: Flag for law enforcement review",
                "Preserve evidence (screenshots, post metadata, author history)",
                "Check author's other recent posts for escalation pattern",
                "Review associated network cluster for coordinated activity",
            ])
        elif threat_category == "Inflammatory":
            actions.extend([
                "Monitor for escalation to violence-inciting content",
                "Identify associated hashtags for counter-narrative deployment",
                "Review author's posting history for radicalization trajectory",
            ])
        elif threat_category == "FakeNews":
            actions.extend([
                "Cross-reference claims with verified news sources",
                "Check content origin and spread pattern for coordinated amplification",
                "Prepare counter-narrative or fact-check advisory",
            ])

        if bot_cluster_id:
            actions.append(
                f"Investigate bot cluster {bot_cluster_id} for coordinated campaign"
            )

        if severity >= 4:
            actions.append("Escalate to senior analyst within 30 minutes")
            actions.append("Prepare preliminary incident report for stakeholders")

        if severity >= 5:
            actions.insert(0, "🚨 CRITICAL: Immediate supervisor notification required")

        return actions

    def render_escalation_notice(
        self,
        alert: dict[str, Any],
        post: Optional[dict[str, Any]] = None,
        classification: Optional[dict[str, Any]] = None,
    ) -> str:
        """
        Render a full escalation notice.

        Args:
            alert: Alert data matching alert_schema.json.
            post: Optional post data matching post_schema.json.
            classification: Optional classification data.

        Returns:
            Formatted escalation notice string.
        """
        severity = alert.get("severity", 1)
        threat_category = alert.get("threat_category", "Unknown")
        bot_cluster_id = alert.get("bot_cluster_id")

        # Build template context
        ctx = {
            "alert_id": alert.get("alert_id", "UNKNOWN"),
            "severity": severity,
            "timestamp": alert.get("created_at", datetime.now(timezone.utc).isoformat()),
            "threat_category": threat_category,
            "triggering_reason": alert.get("triggering_reason", ""),
            "bot_cluster_id": bot_cluster_id,
            "confidence": 0.0,
            "post_text": "",
            "platform": "unknown",
            "author_handle": "unknown",
            "author_id": "unknown",
            "detected_language": "unknown",
            "geo_location": None,
            "post_created_at": "",
            "likes": 0,
            "shares": 0,
            "comments": 0,
            "sentiment": None,
            "sentiment_intensity": 0.0,
            "recommended_actions": self._get_recommended_actions(
                threat_category, severity, bot_cluster_id
            ),
        }

        # Enrich from post data
        if post:
            ctx.update({
                "post_text": post.get("text", ""),
                "platform": post.get("platform", "unknown"),
                "author_handle": post.get("author_handle", "unknown"),
                "author_id": post.get("author_id", "unknown"),
                "detected_language": post.get("language_hint", "unknown"),
                "post_created_at": post.get("created_at", ""),
                "likes": post.get("engagement_counts", {}).get("likes", 0),
                "shares": post.get("engagement_counts", {}).get("shares", 0),
                "comments": post.get("engagement_counts", {}).get("comments", 0),
            })
            geo = post.get("geo_location")
            if geo:
                ctx["geo_location"] = geo.get("place_name", "Unknown")

        # Enrich from classification data
        if classification:
            ctx.update({
                "confidence": classification.get("threat_confidence", 0.0),
                "sentiment": classification.get("sentiment"),
                "sentiment_intensity": classification.get("sentiment_intensity", 0.0),
                "detected_language": classification.get("detected_language", ctx["detected_language"]),
            })

        if self._jinja_available:
            return self._notice_tmpl.render(**ctx)
        else:
            return self._fallback_render(ctx)

    def render_brief_alert(
        self,
        alert: dict[str, Any],
        post: Optional[dict[str, Any]] = None,
        classification: Optional[dict[str, Any]] = None,
    ) -> str:
        """Render a brief alert message for SMS/webhook push."""
        ctx = {
            "alert_id": alert.get("alert_id", "UNKNOWN"),
            "severity": alert.get("severity", 1),
            "threat_category": alert.get("threat_category", "Unknown"),
            "triggering_reason": alert.get("triggering_reason", ""),
            "platform": post.get("platform", "unknown") if post else "unknown",
            "author_handle": post.get("author_handle", "unknown") if post else "unknown",
            "confidence": (
                classification.get("threat_confidence", 0.0) if classification else 0.0
            ),
        }

        if self._jinja_available:
            return self._brief_tmpl.render(**ctx).strip()
        else:
            return (
                f"[NETRA ALERT] Severity {ctx['severity']}/5 — "
                f"{ctx['threat_category']} on {ctx['platform']} "
                f"by {ctx['author_handle']}. Alert: {ctx['alert_id']}"
            )

    def _fallback_render(self, ctx: dict) -> str:
        """Simple fallback rendering without Jinja2."""
        lines = [
            "=" * 70,
            "  NETRA — AUTOMATED ESCALATION NOTICE",
            "=" * 70,
            f"Alert ID:       {ctx['alert_id']}",
            f"Severity:       {ctx['severity']}/5",
            f"Classification: {ctx['threat_category']}",
            f"Timestamp:      {ctx['timestamp']}",
            "",
            f"REASON: {ctx['triggering_reason']}",
            "",
            f"Platform: {ctx['platform']}  |  Author: {ctx['author_handle']}",
            f"Language: {ctx['detected_language']}  |  Location: {ctx['geo_location'] or 'N/A'}",
            "",
        ]
        if ctx.get("post_text"):
            lines.append(f"POST: {ctx['post_text'][:300]}...")
        lines.append("=" * 70)
        return "\n".join(lines)


# ── Convenience Function ────────────────────────────────────────────────────


def generate_escalation_notice(
    alert: dict, post: dict | None = None, classification: dict | None = None
) -> str:
    """Generate an escalation notice from alert/post/classification data."""
    renderer = EscalationTemplateRenderer()
    return renderer.render_escalation_notice(alert, post, classification)
